name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.228.189.173 << 'EOF'
            ls
            cd Portifolio
            git pull origin main
            # Comandos para iniciar o backend
            cd Portifolio/my-app/backend
            node index.js
            pm2 restart index.js
          EOF
